describe("plugin/jksearch.vim", function()
  it("defines the user commands", function()
    assert.is_true(vim.fn.exists(":JKSearch") > 0)
    assert.is_true(vim.fn.exists(":JKSearchInit") > 0)
  end)

  it("exposes the Lua API", function()
    local jksearch = require("jksearch")
    assert.is_function(jksearch.command)
    assert.is_function(jksearch.search_cursor)
    assert.is_function(jksearch.init)
  end)

  it("loads the word helper module", function()
    local word = require("jksearch.word")
    assert.is_function(word.truncate)
    assert.is_function(word.compound_noun)
  end)
end)
